### ISSUE TITLE
Colors and fontsíze

### ISSUE THREAD

**Issue by gtbu** [ProfessionalWiki/FontAwesome#6]
At the moment i the icons are black. Is it possible to colorize them and adjust the size as with the ckeditor-FA-plugins . At the moment  i prefer to load the Fa-all.css from the web which allows that.

**Comment by s7eph4n** [comment]
This extension just loads the necessary files without any customization. 

However, you can easily modify the styles by e.g. adding a rule to ``MediaWiki:Common.css``. I did not try it, but something like this should work:
``` css
.fa,
.fas,
.far,
.fal,
.fad,
.fab {
  color: red;
}
```
